### ISSUE TITLE
Incorrect error with from --creds un:pwd when creds are invalid

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [projectatomic/buildah#401]
**Description**

buildah pull from --creds un:pwd gives a bad error message when the creds are invalid.  Rather than showing an error in the creds, it says image not found.

**Steps to reproduce the issue:**
1.  Setup a private repository with credentials
2.  push an image to it
3.  pull image with creds that are incorrect.

You can use https://raw.githubusercontent.com/projectatomic/buildah/master/tests/test_buildah_authentication.sh and comment out the last five line in the comment section.  On a machine with Docker and Buildah (0.11) installed run:

```
/bin/bash -v test_buildah_authentication.sh
buildah from localhost:5000/my-commit-alpine --pull-always --cert-dir /root/auth  --tls-verify=true --creds=testuser:badpassword
```

**Describe the results you received:**
```
# buildah from localhost:5000/my-commit-alpine --pull-always --cert-dir /root/auth  --tls-verify=true --creds=testuser:testpasswo
no such image "localhost:5000/my-commit-alpine": image not known
```

**Describe the results you expected:**
A better error message is displayed showing the errror.

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah-0.11-1.git6bad262.fc27.x86_64
```

**Output of `buildah version`:**

```
# buildah version
Version:       0.11
Go Version:    go1.9.2
Image Spec:    1.0.0
Runtime Spec:  1.0.0
Git Commit:    6bad262
Built:         Wed Jan 17 08:49:14 2018
OS/Arch:       linux/amd64
```

**Output of `cat /etc/*release`:**

```
# cat /etc/*release
Fedora release 27 (Twenty Seven)
NAME=Fedora
VERSION="27 (Server Edition)"
ID=fedora
VERSION_ID=27
PRETTY_NAME="Fedora 27 (Server Edition)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:fedoraproject:fedora:27"
HOME_URL="https://fedoraproject.org/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=27
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=27
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Server Edition"
VARIANT_ID=server
Fedora release 27 (Twenty Seven)
Fedora release 27 (Twenty Seven)

```

**Output of `uname -a`:**

```
# uname -a
Linux localhost.localdomain 4.14.3-300.fc27.x86_64 #1 SMP Mon Dec 4 17:18:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
# cat /etc/containers/storage.conf
# storage.conf is the configuration file for all tools
# that share the containers/storage libraries
# See man 5 containers-storage.conf for more information

# The "container storage" table contains all of the server options.
[storage]

# Default Storage Driver
driver = "overlay"

# Temporary storage location
runroot = "/var/run/containers/storage"

# Primary Read/Write location of container storage
graphroot = "/var/lib/containers/storage"

[storage.options]
# AdditionalImageStores is used to pass paths to additional Read/Only image stores
# Must be comma separated list.
additionalimagestores = [
]

# Size is used to set a maximum size of the container image.  Only supported by
# certain container storage drivers.
size = ""

# OverrideKernelCheck tells the driver to ignore kernel checks based on kernel version
override_kernel_check = "true"

```

**Comment by gouyang** [comment]
See the same issue on the master

**Comment by ripcurld0** [comment]
@TomSweeneyRedHat when I run `/bin/bash -v tests/test_buildah_authentication.sh` the registry is not running. Doing `docker logs registry` prints the following:
```
time="2018-01-23T13:43:05Z" level=warning msg="No HTTP secret provided - generated random secret. This may cause problems with uploads if multiple registries a
re behind a load-balancer. To provide a shared secret, fill in http.secret in the configuration file or set the REGISTRY_HTTP_SECRET environment variable." go.
version=go1.7.6 instance.id=8d6829f0-dbbd-4b63-b45d-c30180fe5666 version=v2.6.2
time="2018-01-23T13:43:05Z" level=info msg="redis not configured" go.version=go1.7.6 instance.id=8d6829f0-dbbd-4b63-b45d-c30180fe5666 version=v2.6.2           
time="2018-01-23T13:43:05Z" level=info msg="Starting upload purge in 55m0s" go.version=go1.7.6 instance.id=8d6829f0-dbbd-4b63-b45d-c30180fe5666 version=v2.6.2 
time="2018-01-23T13:43:05Z" level=info msg="using inmemory blob descriptor cache" go.version=go1.7.6 instance.id=8d6829f0-dbbd-4b63-b45d-c30180fe5666 version=v
2.6.2                                                                                                                                                          
panic: unable to configure authorization (htpasswd): "path" must be set for htpasswd access controller
                                                                               
goroutine 1 [running]:                                                                                                                                         
panic(0xb4ccc0, 0xc4203c8110)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/docker/distribution/registry/handlers.NewApp(0x1066800, 0xc4203aa4e0, 0xc42036ea80, 0x1066800)
        /go/src/github.com/docker/distribution/registry/handlers/app.go:302 +0x1b6a
github.com/docker/distribution/registry.NewRegistry(0x7f778db46040, 0xc4203aa4e0, 0xc42036ea80, 0xc42036ea80, 0x0, 0x0)
        /go/src/github.com/docker/distribution/registry/registry.go:86 +0x213
github.com/docker/distribution/registry.glob..func1(0x108e180, 0xc420398460, 0x1, 0x1)
        /go/src/github.com/docker/distribution/registry/registry.go:55 +0x106
github.com/docker/distribution/vendor/github.com/spf13/cobra.(*Command).execute(0x108e180, 0xc420398410, 0x1, 0x1, 0x108e180, 0xc420398410)
        /go/src/github.com/docker/distribution/vendor/github.com/spf13/cobra/command.go:495 +0x190
github.com/docker/distribution/vendor/github.com/spf13/cobra.(*Command).Execute(0x108e320, 0xc4201b5f40, 0xc4200001a0)
        /go/src/github.com/docker/distribution/vendor/github.com/spf13/cobra/command.go:560 +0x3c3
main.main()
        /go/src/github.com/docker/distribution/cmd/registry/main.go:24 +0x2d
```

**Comment by TomSweeneyRedHat** [comment]
@ripcurld0 Which distro/version were you running on?  RHEL?  It worked for me the other day on F27.  Also the golang you're using appears to be v1.7.  Any chance you could bump that up to 1.8 or higher?

I've not run into the REGISTRY_HTTP_SECRET error before, will have to dig into that a bit.

**Comment by ripcurld0** [comment]
Yeah, I figured out why it didn't work: bad configurations.
I will continue and try to investigate this problem.

Thank for your fast response. @TomSweeneyRedHat

**Comment by ripcurld0** [comment]
OK, I think I know what is the problem:
During the [`util.ResolveName` loop](https://github.com/projectatomic/buildah/blob/master/new.go#L133) since the `pull-always` flag is set to true the image is pulled [here](https://github.com/projectatomic/buildah/blob/master/new.go#L144) by calling to [pullAndFindImage](https://github.com/projectatomic/buildah/blob/master/new.go#L66). However, this function returns an [error](https://github.com/projectatomic/buildah/blob/master/new.go#L69) which is printed under severity DEBUG as you can see [here](https://github.com/projectatomic/buildah/blob/master/new.go#L146) and then continue to the next image in the loop. However, in this particular case there is no available image and so `ref` and `img` are both `nil` and thus "no such image" error is printed.

If you don't mind, I think I know how to resolve this. Hence, I am going to assign this to myself but feel free to change that if you like.

**Comment by TomSweeneyRedHat** [comment]
@ripcurld0 nice catch, please do run with it.

**Comment by rhatdan** [comment]
@ripcurld0 Feel free to assign any issue you want to deal with.  No need to ask.
