### ISSUE TITLE
0.13 segfaults trying to run containers created with a previous version

### ISSUE THREAD

**Issue by alatiera** [projectatomic/buildah#497]
**Description**
I am running `fedora atomic WS rawhide`, today I upgraded from `buldah 0.12`(sorry don't really know the hash, but still have the previous `os-tree`) to `buildah-0.13-1.gitef0ca9c.fc29.x86_64`.

After trying to run any container that was created previously it segfaults. Creating new containers from the same image and passing them the same arguments works though.

**Steps to reproduce the issue:**
1. Create a container with 0.12
2. Try to run it in 0.13
3. Watch it segfault

**Describe the results you received:**

```sh
➜  ~ sudo buildah run fedora-working-container -- bash
[sudo] password for alatiera: 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x9f6527]

goroutine 1 [running]:
github.com/projectatomic/buildah.addCommonOptsToSpec(0x0, 0xc4204d10d0, 0x3, 0xc42002598b)
	/builddir/build/BUILD/buildah-ef0ca9cd2d69e8ca70d07e19386c676ae4985644/_build/src/github.com/projectatomic/buildah/run.go:111 +0x37
github.com/projectatomic/buildah.(*Builder).Run(0xc4200bdb00, 0xc42001e180, 0x1, 0x1, 0x0, 0x0, 0xbb1e8d, 0x4, 0x11d7410, 0x0, ...)
	/builddir/build/BUILD/buildah-ef0ca9cd2d69e8ca70d07e19386c676ae4985644/_build/src/github.com/projectatomic/buildah/run.go:263 +0x3c8
main.runCmd(0xc420311680, 0x0, 0xc420311680)
	/builddir/build/BUILD/buildah-ef0ca9cd2d69e8ca70d07e19386c676ae4985644/cmd/buildah/run.go:116 +0x873
github.com/urfave/cli.HandleAction(0xab8000, 0xbe8c48, 0xc420311680, 0xc420506600, 0x0)
	/builddir/build/BUILD/buildah-ef0ca9cd2d69e8ca70d07e19386c676ae4985644/src/github.com/urfave/cli/app.go:485 +0xc8
github.com/urfave/cli.Command.Run(0xbb19e9, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0xbca8d9, 0x25, 0x0, ...)
	/builddir/build/BUILD/buildah-ef0ca9cd2d69e8ca70d07e19386c676ae4985644/src/github.com/urfave/cli/command.go:207 +0xa35
github.com/urfave/cli.(*App).Run(0xc4200a84e0, 0xc42001e140, 0x5, 0x5, 0x0, 0x0)
	/builddir/build/BUILD/buildah-ef0ca9cd2d69e8ca70d07e19386c676ae4985644/src/github.com/urfave/cli/app.go:250 +0x700
main.main()
	/builddir/build/BUILD/buildah-ef0ca9cd2d69e8ca70d07e19386c676ae4985644/cmd/buildah/main.go:107 +0xc17
```

**Describe the results you expected:**

A shell into the container

**Output of `rpm -q buildah` or `apt list buildah`:**

```sh
buildah-0.13-1.gitef0ca9c.fc29.x86_64
```

**Output of `buildah version`:**

```sh
➜  ~ buildah -v
buildah version 0.13 (image-spec 1.0.0, runtime-spec 1.0.0)
```

**Output of `cat /etc/*release`:**

```sh
➜  ~ cat /etc/redhat-release 
Fedora release 29 (Rawhide)
➜  ~ rpm-ostree status
State: idle; auto updates disabled
Deployments:
● ostree://fedora-ws-rawhide:fedora/rawhide/x86_64/workstation
                   Version: Rawhide.20180224.n.0 (2018-02-24 08:32:38)
                BaseCommit: 93684dd9baa7386a079c33b494cb541b2eef084af3c71e7c0cc5159c3f5262c0
              GPGSignature: Valid signature by 128CF232A9371991C8A65695E08E7E629DB62FB1
           LayeredPackages: exa fish gnome-terminal-nautilus ripgrep tilix

```

**Output of `uname -a`:**

```sh
Linux localhost.localdomain 4.16.0-0.rc2.git3.1.fc29.x86_64 #1 SMP Fri Feb 23 15:00:21 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```sh
➜  ~ cat /etc/containers/storage.conf 
# storage.conf is the configuration file for all tools
# that share the containers/storage libraries
# See man 5 containers-storage.conf for more information

# The "container storage" table contains all of the server options.
[storage]

# Default Storage Driver
driver = "overlay"

# Temporary storage location
runroot = "/var/run/containers/storage"

# Primary Read/Write location of container storage
graphroot = "/var/lib/containers/storage"

[storage.options]
# AdditionalImageStores is used to pass paths to additional Read/Only image stores
# Must be comma separated list.
additionalimagestores = [
]

# Size is used to set a maximum size of the container image.  Only supported by
# certain container storage drivers.
size = ""

# OverrideKernelCheck tells the driver to ignore kernel checks based on kernel version
override_kernel_check = "true"
```

**Comment by TomSweeneyRedHat** [comment]
@alatiera Thanks for the issue report.   After v0.12 we vendored in containers/storage and containers/image.  I'm guessing that's causing the issue.  @rhatdan @nalind any other thoughts?  Sounds like a release note for v0.13 when it goes out.

**Comment by alatiera** [comment]
The previous version I was using of Buildah btw was:

Output of `rpm -q buildah`
`buildah-0.12-1.git8badcc2.fc28.x86_64`

and the full output of `rpm-ostree status -v`
```sh
➜  ~ rpm-ostree status -v
State: idle; auto updates disabled
Deployments:
  ostree://fedora-ws-rawhide:fedora/rawhide/x86_64/workstation
                   Version: Rawhide.20180224.n.0 (2018-02-24 08:32:38)
                BaseCommit: 93684dd9baa7386a079c33b494cb541b2eef084af3c71e7c0cc5159c3f5262c0
                    Commit: e8a10f7786561cb70ddd06858c57809d088a62b833d6079a04dd5ce50b6bab8f
                 StateRoot: fedora-workstation
              GPGSignature: 1 signature
                            Signature made Sat 24 Feb 2018 10:32:49 AM EET using RSA key ID E08E7E629DB62FB1
                            Good signature from "Fedora 28 <fedora-28@fedoraproject.org>"
  InactiveBaseReplacements: flatpak-0.11.3-1.fc28.x86_64 flatpak-libs-0.11.3-1.fc28.x86_64
           LayeredPackages: exa fish gnome-terminal-nautilus ripgrep tilix

● ostree://fedora-ws-rawhide:fedora/rawhide/x86_64/workstation
                   Version: Rawhide.20180222.n.1 (2018-02-23 01:29:03)
                BaseCommit: 21ac24694b6e308de29b35057c337c2048b71ddca7a1603742ad0f1b6494d798
                    Commit: c24a66b90e648aac46637af28403781b08fd3d89621470908fb0f012e6e79876
                 StateRoot: fedora-workstation
              GPGSignature: 1 signature
                            Signature made Fri 23 Feb 2018 03:29:10 AM EET using RSA key ID E08E7E629DB62FB1
                            Good signature from "Fedora 28 <fedora-28@fedoraproject.org>"
  InactiveBaseReplacements: flatpak-0.11.3-1.fc28.x86_64 flatpak-libs-0.11.3-1.fc28.x86_64
           LayeredPackages: exa fish gnome-terminal-nautilus ripgrep tilix
```

**Comment by rhatdan** [comment]
@alatiera Could you try this patch and see if it fixes your problem.

**Comment by alatiera** [comment]
@rhatdan yea sure. Do I need to spin it as an `rpm` and override my `os-tree` or `go get` would work?

**Comment by alatiera** [comment]
I followed the [installation notes](https://github.com/projectatomic/buildah/blob/master/install.md), cloned https://github.com/rhatdan/buildah/tree/segfault and built a binary that I copied to my host system.

I don't think it worked though. I might failed something too. Can I get the binary to print the commit hash it was built from in any way? `buildah -v` shows the same as my host install.
```shell
➜  projects ./buildah -v
buildah version 0.13 (image-spec 1.0.0, runtime-spec 1.0.0)
```

```shell
➜  projects sudo ./buildah run fedora-working-container -- bash
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xa2d527]

goroutine 1 [running]:
github.com/projectatomic/buildah.addCommonOptsToSpec(0x0, 0xc4204cd078, 0x3, 0xc420081334)
	/root/buildah/src/github.com/projectatomic/buildah/run.go:111 +0x37
github.com/projectatomic/buildah.(*Builder).Run(0xc4200a7b00, 0xc420086130, 0x1, 0x1, 0x0, 0x0, 0xbeb01f, 0x4, 0x1252938, 0x0, ...)
	/root/buildah/src/github.com/projectatomic/buildah/run.go:263 +0x3ec
main.runCmd(0xc4203f3a40, 0x0, 0xc4203f3a40)
	/root/buildah/src/github.com/projectatomic/buildah/cmd/buildah/run.go:116 +0x895
github.com/projectatomic/buildah/vendor/github.com/urfave/cli.HandleAction(0xaf43a0, 0xc208c0, 0xc4203f3a40, 0xc420382600, 0x0)
	/root/buildah/src/github.com/projectatomic/buildah/vendor/github.com/urfave/cli/app.go:485 +0xd2
github.com/projectatomic/buildah/vendor/github.com/urfave/cli.Command.Run(0xbeab83, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc03175, 0x25, 0x0, ...)
	/root/buildah/src/github.com/projectatomic/buildah/vendor/github.com/urfave/cli/command.go:207 +0xa99
github.com/projectatomic/buildah/vendor/github.com/urfave/cli.(*App).Run(0xc42007c4e0, 0xc4200860f0, 0x5, 0x5, 0x0, 0x0)
	/root/buildah/src/github.com/projectatomic/buildah/vendor/github.com/urfave/cli/app.go:250 +0x758
main.main()
	/root/buildah/src/github.com/projectatomic/buildah/cmd/buildah/main.go:107 +0xc34

```

**Comment by alatiera** [comment]
yea, sure will do in a bit!

**Comment by alatiera** [comment]
@rhatdan I don't see any new commit nor any `push -f` indication in the MR. Where is the new patch located?

**Comment by rhatdan** [comment]
I did a push --force, to replace the original.  Very minor change, I was checking if the options were not nil and returning, when should have been checking if nil.

**Comment by alatiera** [comment]
Still segfaults, but now I think it hits a new one.

```shell
➜  projects sudo ./buildah run fedora-working-container -- bash
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xa0 pc=0xa1aa41]

goroutine 1 [running]:
github.com/projectatomic/buildah.(*Builder).Run(0xc420489200, 0xc420010180, 0x1, 0x1, 0x0, 0x0, 0xbece5c, 0x4, 0x12549f8, 0x0, ...)
	/root/buildah/src/github.com/projectatomic/buildah/run.go:410 +0xea1
main.runCmd(0xc4204f4b40, 0x0, 0xc4204f4b40)
	/root/buildah/src/github.com/projectatomic/buildah/cmd/buildah/run.go:116 +0x895
github.com/projectatomic/buildah/vendor/github.com/urfave/cli.HandleAction(0xaf6280, 0xc22928, 0xc4204f4b40, 0xc4204e8300, 0x0)
	/root/buildah/src/github.com/projectatomic/buildah/vendor/github.com/urfave/cli/app.go:485 +0xd2
github.com/projectatomic/buildah/vendor/github.com/urfave/cli.Command.Run(0xbec9c4, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc050b2, 0x25, 0x0, ...)
	/root/buildah/src/github.com/projectatomic/buildah/vendor/github.com/urfave/cli/command.go:207 +0xa99
github.com/projectatomic/buildah/vendor/github.com/urfave/cli.(*App).Run(0xc4200784e0, 0xc420010140, 0x5, 0x5, 0x0, 0x0)
	/root/buildah/src/github.com/projectatomic/buildah/vendor/github.com/urfave/cli/app.go:250 +0x758
main.main()
	/root/buildah/src/github.com/projectatomic/buildah/cmd/buildah/main.go:107 +0xc34
```

The first line now is diff now `/root/buildah/src/github.com/projectatomic/buildah/run.go:410 +0xea1`

where previous it was `/root/buildah/src/github.com/projectatomic/buildah/run.go:111 +0x37`

**Comment by rhatdan** [comment]
Looking at this further, I think we had a breaking change.  I think we will have to just say the older containers are no longer supported after upgrade.  You would have to commit the old containers and then work on them.

**Comment by alatiera** [comment]
Okay will do that, thanks! 

Would it be possible to have it show an error message instead of segfaulting? Other people might be confused later on.

**Comment by rhatdan** [comment]
Yes I just added an error message to 0.14 and am working on cutting 0.15.  Thanks for finding this, and hopefully we will be better about breaking backwards compatibility in the future.  But that is why this is tech preview.  :^(

**Comment by rhatdan** [comment]
buildah-0.15 should fix this issue.
